export const GET_PRODUCTS = "GET_PRODUCTS";

export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const CONFIRM_ORDER_DISH = "CONFIRM_ORDER_DISH";
export const SHOW_SUMMARY = "SHOW_SUMMARY";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
